"""add_autoincrement_to_all_primary_keys

Revision ID: 121d5edfdf4e
Revises: 658e68e87fec
Create Date: 2025-08-23 12:06:10.635655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '121d5edfdf4e'
down_revision = '658e68e87fec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

