"""Add Session and Speaker models

Revision ID: 480ab9a6dc6d
Revises: 7d2efd9f2ea2
Create Date: 2025-08-21 12:44:02.736818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '480ab9a6dc6d'
down_revision = '7d2efd9f2ea2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('sessions', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('sessions', 'start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('sessions', 'end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_column('sessions', 'capacity')
    op.add_column('speakers', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('speakers', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('speakers', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('speakers', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('speakers', 'bio',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('speakers', 'phone',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index('ix_speakers_email', table_name='speakers')
    op.create_unique_constraint(None, 'speakers', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'speakers', type_='unique')
    op.create_index('ix_speakers_email', 'speakers', ['email'], unique=False)
    op.alter_column('speakers', 'phone',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('speakers', 'bio',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('speakers', 'updated_at')
    op.drop_column('speakers', 'created_at')
    op.drop_column('speakers', 'is_active')
    op.drop_column('speakers', 'company')
    op.add_column('sessions', sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('sessions', 'end_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('sessions', 'start_time',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.drop_column('sessions', 'is_active')
    op.drop_column('sessions', 'description')
    # ### end Alembic commands ###

