"""Update all models with latest changes

Revision ID: 7d2efd9f2ea2
Revises: 92c7be698140
Create Date: 2025-08-21 12:40:52.558450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d2efd9f2ea2'
down_revision = '92c7be698140'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

