"""Update models with correct relationships

Revision ID: 92c7be698140
Revises: dd18301e25b3
Create Date: 2025-08-21 12:38:37.420580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92c7be698140'
down_revision = 'dd18301e25b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'event_registrations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_registrations', type_='foreignkey')
    # ### end Alembic commands ###

