"""Update Event table

Revision ID: 9f352968aea7
Revises: f2b49927d637
Create Date: 2025-08-20 13:32:25.464885

"""
from alembic import op
import sqlalchemy as sa


# identificadores de revisión, utilizados por Alembic.
revision = '9f352968aea7'
down_revision = 'f2b49927d637'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
